apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: greeting
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: flask_example
        - name: MYSQL_USER
          value: flaskuser
        - name: MYSQL_PASSWORD
          value: flaskpwd!
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-deployment
  namespace: greeting
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP